[package]
name = "common-grpc"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
api = { path = "../../api" }
arrow-flight.workspace = true
async-trait = "0.1"
common-base = { path = "../base" }
common-error = { path = "../error" }
common-query = { path = "../query" }
common-recordbatch = { path = "../recordbatch" }
common-runtime = { path = "../runtime" }
dashmap = "5.4"
datafusion.workspace = true
datatypes = { path = "../../datatypes" }
flatbuffers = "23.1"
futures = "0.3"
prost.workspace = true
snafu = { version = "0.7", features = ["backtraces"] }
tokio.workspace = true
tonic.workspace = true
tower = "0.4"

[dev-dependencies]
criterion = "0.4"
rand.workspace = true

[[bench]]
name = "bench_main"
harness = false
