repos:
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: 47923ce11be4a936cd216d427d985dd342adb751
    hooks:
    -    id: conventional-pre-commit
         stages: [commit-msg]

# -   repo: https://github.com/DevinR528/cargo-sort
#     rev: e6a795bc6b2c0958f9ef52af4863bbd7cc17238f
#     hooks:
#     -    id: cargo-sort
#          args: ["--workspace"]

-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -    id: fmt
         args: ["--", "--check"]
         stages: [commit-msg]
    -    id: clippy
         args: ["--workspace", "--all-targets", "--all-features", "--", "-D", "warnings"]
         stages: [commit-msg]
    -    id: cargo-check
         args: ["--workspace", "--all-targets", "--all-features"]
         stages: [commit-msg]
