[default.extend-words]
Pn = "Pn"
ue = "ue"
worl = "worl"
ot = "ot"
unqualifed = "unqualifed"

[files]
extend-exclude = [
    "corrupted",
    "tests-fuzz/src/data/lorem_words",
    "*.sql",
    "*.result",
    "src/pipeline/benches/data.log"
]
