[default.extend-words]
Pn = "Pn"
ue = "ue"
worl = "worl"
ot = "ot"
typ = "typ"
typs = "typs"
unqualifed = "unqualifed"
excluder = "excluder"

[files]
extend-exclude = [
    "corrupted",
    "tests-fuzz/src/data/lorem_words",
    "*.sql",
    "*.result",
    "src/pipeline/benches/data.log",
    "cyborg/pnpm-lock.yaml"
]
