[package]
name = "common-recordbatch"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arc-swap = "1.6"
common-base.workspace = true
common-error.workspace = true
common-macro.workspace = true
datafusion-common.workspace = true
datafusion.workspace = true
datatypes.workspace = true
futures.workspace = true
paste = "1.0"
serde.workspace = true
serde_json.workspace = true
snafu.workspace = true

[dev-dependencies]
tokio.workspace = true
