[package]
name = "common-recordbatch"
version = "0.1.0"
edition = "2021"

[dependencies]
common-error = { path = "../error" }
datafusion = { git = "https://github.com/apache/arrow-datafusion.git" , branch = "arrow2", features = ["simd"]}
datafusion-common = { git = "https://github.com/apache/arrow-datafusion.git" , branch = "arrow2"}
datatypes = { path = "../../datatypes" }
futures = "0.3"
paste = "1.0"
serde = "1.0"
snafu = { version = "0.7", features = ["backtraces"] }

[dev-dependencies]
serde_json = "1.0"
tokio = { version = "1.18", features = ["full"] }
