[package]
name = "common-recordbatch"
version = "0.1.0"
edition = "2021"

[dependencies]
datafusion = { git = "https://github.com/apache/arrow-datafusion.git" , branch = "arrow2", features = ["simd"]}
datafusion-common = { git = "https://github.com/apache/arrow-datafusion.git" , branch = "arrow2"}
datatypes = { path = "../../datatypes" }
futures = "0.3"
paste = "1.0"
serde = "1.0"
snafu = { version = "0.7", features = ["backtraces"] }


[dev-dependencies.arrow]
package = "arrow2"
version="0.10"
features = ["io_csv", "io_json", "io_parquet", "io_parquet_compression", "io_ipc", "ahash", "compute", "serde_types"]

[dev-dependencies]
serde_json = "1.0"
tokio = { version = "1.18", features = ["full"] }

