[package]
name = "cmd"
version = "0.1.0"
edition = "2021"
default-run = "greptime"

[[bin]]
name = "greptime"
path = "src/bin/greptime.rs"

[dependencies]
clap = { version = "3.1", features = ["derive"] }
common-error = { path = "../common/error" }
common-telemetry = { path = "../common/telemetry", features = [
    "deadlock_detection",
] }
datanode = { path = "../datanode" }
frontend = { path = "../frontend" }
futures = "0.3"
meta-srv = { path = "../meta-srv" }
snafu = { version = "0.7", features = ["backtraces"] }
tokio = { version = "1.18", features = ["full"] }
toml = "0.5"

[dev-dependencies]
serde = "1.0"
tempdir = "0.3"
