[package]
name = "log-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[build-dependencies]
protobuf-build = { version = "0.15", default-features = false, features = [
    "protobuf-codec",
] }

[dependencies]
async-stream.workspace = true
async-trait.workspace = true
base64 = "0.13"
byteorder = "1.4"
bytes = "1.1"
common-base = { workspace = true }
common-config = { workspace = true }
common-error = { workspace = true }
common-meta = { workspace = true }
common-runtime = { workspace = true }
common-telemetry = { workspace = true }
futures-util.workspace = true
futures.workspace = true
protobuf = { version = "2", features = ["bytes"] }
raft-engine = { git = "https://github.com/tikv/raft-engine.git", rev = "2dcaf5beeea3d5de9ec9c7133a2451d00f508f52" }
snafu = { version = "0.7", features = ["backtraces"] }
store-api = { workspace = true }
tokio-util.workspace = true
tokio.workspace = true

[dev-dependencies]
common-test-util = { workspace = true }
rand.workspace = true
