[package]
name = "log-store"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-stream = "0.3"
async-trait = "0.1"
base64 = "0.13"
byteorder = "1.4"
bytes = "1.1"
common-error = { path = "../common/error" }
common-telemetry = { path = "../common/telemetry" }
crc = "3.0"
futures = "0.3"
futures-util = "0.3"
hex = "0.4"
memmap2 = "0.5"
snafu = { version = "0.7", features = ["backtraces"] }
store-api = { path = "../store-api" }
tokio = { version = "1.18", features = ["full"] }

[dev-dependencies]
tempdir = "0.3"
rand = "0.8.5"