[package]
name = "log-store"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
arc-swap = "1.5"
async-stream = "0.3"
async-trait = "0.1"
base64 = "0.13"
byteorder = "1.4"
bytes = "1.1"
common-base = { path = "../common/base" }
common-error = { path = "../common/error" }
common-runtime = { path = "../common/runtime" }
common-telemetry = { path = "../common/telemetry" }
crc = "3.0"
futures = "0.3"
futures-util = "0.3"
hex = "0.4"
snafu = { version = "0.7", features = ["backtraces"] }
store-api = { path = "../store-api" }
tempdir = "0.3"
tokio = { version = "1.18", features = ["full"] }
tokio-util = "0.7"

[dev-dependencies]
rand = "0.8"
criterion = { version = "0.4", features = ["async_tokio"] }

[[bench]]
name = "bench_main"
harness = false

