[package]
name = "log-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[build-dependencies]
protobuf-build = { version = "0.14", default-features = false, features= ["protobuf-codec"] }

[dependencies]
async-trait.workspace = true
arc-swap = "1.5"
async-stream.workspace = true
base64 = "0.13"
byteorder = "1.4"
bytes = "1.1"
common-base = { path = "../common/base" }
common-error = { path = "../common/error" }
common-runtime = { path = "../common/runtime" }
common-telemetry = { path = "../common/telemetry" }
crc = "3.0"
futures.workspace = true
futures-util = "0.3"
hex = "0.4"
snafu = { version = "0.7", features = ["backtraces"] }
store-api = { path = "../store-api" }
tempdir = "0.3"
tokio = { version = "1.18", features = ["full"] }
tokio-util = "0.7"
protobuf = { version = "2", features=["bytes"] }

[dev-dependencies]
rand = "0.8"
