[package]
name = "common-greptimedb-telemetry"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
common-error = { workspace = true }
common-runtime = { workspace = true }
common-telemetry = { workspace = true }
once_cell = "1.17.0"
reqwest = { version = "0.11", features = [
    "json",
    "rustls-tls",
], default-features = false }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
uuid.workspace = true

[dev-dependencies]
common-test-util = { workspace = true }
hyper = { version = "0.14", features = ["full"] }

[build-dependencies]
common-version = { workspace = true }
