[package]
name = "common-options"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
common-grpc.workspace = true
humantime-serde.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
