[package]
name = "meta-client"
version = "0.1.0"
edition = "2021"

[dependencies]
api = { path = "../api" }
async-trait = "0.1"
common-error = { path = "../common/error" }
common-grpc = { path = "../common/grpc" }
common-telemetry = { path = "../common/telemetry" }
etcd-client = "0.10"
rand = "0.8"
snafu = { version = "0.7", features = ["backtraces"] }
tokio = { version = "1.18", features = ["full"] }
tokio-stream = { version = "0.1", features = ["net"] }
tonic = "0.8"

[dev-dependencies]
futures = "0.3"
meta-srv = { path = "../meta-srv", features = ["mock"]}
tower = "0.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
