[package]
name = "common-datasource"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arrow-schema.workspace = true
arrow.workspace = true
async-compression = { version = "0.3", features = [
    "bzip2",
    "gzip",
    "xz",
    "zstd",
    "futures-io",
    "tokio",
] }
async-trait.workspace = true
bytes.workspace = true
common-error.workspace = true
common-macro.workspace = true
common-runtime.workspace = true
datafusion.workspace = true
datatypes.workspace = true
derive_builder.workspace = true
futures.workspace = true
lazy_static.workspace = true
object-store.workspace = true
orc-rust = "0.2"
parquet.workspace = true
paste = "1.0"
regex = "1.7"
serde.workspace = true
snafu.workspace = true
strum.workspace = true
tokio-util.workspace = true
tokio.workspace = true
url = "2.3"

[dev-dependencies]
common-test-util.workspace = true
