[package]
name = "partition"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common-error = { path = "../common/error" }
common-query = { path = "../common/query" }
datafusion.workspace = true
datafusion-common.workspace = true
datafusion-expr.workspace = true
datatypes = { path = "../datatypes" }
meta-client = { path = "../meta-client" }
moka = { version = "0.9", features = ["future"] }
snafu = { version = "0.7", features = ["backtraces"] }
store-api = { path = "../store-api" }
serde = "1.0"
serde_json = "1.0"
table = { path = "../table" }
