[package]
name = "table-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
async-stream = "0.3"
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
common-error = {path = "../common/error" }
common-query = {path = "../common/query" }
common-recordbatch = {path = "../common/recordbatch" }
common-telemetry = {path = "../common/telemetry" }
datafusion-common = { git = "https://github.com/apache/arrow-datafusion.git" , branch = "arrow2"}
datatypes = { path = "../datatypes" }
futures = "0.3"
log-store = { path = "../log-store" }
snafu = { version = "0.7", features = ["backtraces"] }
storage ={ path = "../storage" }
store-api ={ path = "../store-api" }
table = { path = "../table" }
tokio = { version = "1.0", features = ["full"] }

[dev-dependencies]
datatypes = { path = "../datatypes" }
tempdir = "0.3"
tokio = { version = "1.18", features = ["full"] }
