[package]
name = "common-procedure"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
common-error = { path = "../error" }
common-runtime = { path = "../runtime" }
common-telemetry = { path = "../telemetry" }
futures.workspace = true
object-store = { path = "../../object-store" }
serde.workspace = true
serde_json = "1.0"
smallvec = "1"
snafu.workspace = true
tokio.workspace = true
uuid.workspace = true

[dev-dependencies]
futures-util.workspace = true
tempfile = "3.4.0"
