[package]
name = "common-time"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arrow.workspace = true
chrono-tz = "0.8"
chrono.workspace = true
common-error.workspace = true
common-macro.workspace = true
once_cell.workspace = true
serde = { version = "1.0", features = ["derive"] }
serde_json.workspace = true
snafu.workspace = true

[dev-dependencies]
rand.workspace = true
