[package]
name = "common-decimal"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arrow.workspace = true
bigdecimal.workspace = true
common-error.workspace = true
common-macro.workspace = true
rust_decimal.workspace = true
serde.workspace = true
serde_json.workspace = true
snafu.workspace = true
