[package]
name = "common-catalog"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
common-error = { path = "../error" }
serde.workspace = true
serde_json = "1.0"
snafu = { version = "0.7", features = ["backtraces"] }

[dev-dependencies]
chrono.workspace = true
tokio.workspace = true
