[package]
name = "query"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
arc-swap = "1.0"
async-trait = "0.1"
catalog = { path = "../catalog" }
common-catalog = { path = "../common/catalog" }
common-error = { path = "../common/error" }
common-function = { path = "../common/function" }
common-query = { path = "../common/query" }
common-recordbatch = { path = "../common/recordbatch" }
common-telemetry = { path = "../common/telemetry" }
common-time = { path = "../common/time" }
datafusion = "14.0.0"
datafusion-common = "14.0.0"
datafusion-physical-expr = "14.0.0"
datatypes = { path = "../datatypes" }
futures = "0.3"
futures-util = "0.3"
metrics = "0.20"
once_cell = "1.10"
serde = "1.0"
serde_json = "1.0"
session = { path = "../session" }
snafu = { version = "0.7", features = ["backtraces"] }
sql = { path = "../sql" }
table = { path = "../table" }
tokio = "1.0"

[dev-dependencies]
approx_eq = "0.1"
common-function-macro = { path = "../common/function-macro" }
format_num = "0.1"
num = "0.4"
num-traits = "0.2"
paste = "1.0"
rand = "0.8"
statrs = "0.15"
stats-cli = "3.0"
streaming-stats = "0.2"
tokio = { version = "1.0", features = ["full"] }
tokio-stream = "0.1"
