[package]
name = "query"
version = "0.1.0"
edition = "2021"

[dependencies.arrow]
package = "arrow2"
version="0.10"
features = ["io_csv", "io_json", "io_parquet", "io_parquet_compression", "io_ipc", "ahash", "compute", "serde_types"]

[dependencies]
async-trait = "0.1"
common-error = { path = "../common/error" }
common-recordbatch = {path = "../common/recordbatch" }
datafusion = { git = "https://github.com/apache/arrow-datafusion.git" , branch = "arrow2", features = ["simd"]}
datatypes = {path = "../datatypes" }
futures = "0.3"
futures-util = "0.3.21"
snafu = { version = "0.7", features = ["backtraces"] }
table = { path = "../table" }
tokio = "1.0"
sql = { path = "../sql" }

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
tokio-stream = "0.1"
