[package]
name = "query"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
ahash.workspace = true
api.workspace = true
arc-swap = "1.0"
arrow.workspace = true
arrow-schema.workspace = true
async-recursion = "1.0"
async-stream.workspace = true
async-trait = "0.1"
bytes.workspace = true
catalog.workspace = true
chrono.workspace = true
common-base.workspace = true
common-catalog.workspace = true
common-datasource.workspace = true
common-error.workspace = true
common-function.workspace = true
common-macro.workspace = true
common-meta.workspace = true
common-plugins.workspace = true
common-query.workspace = true
common-recordbatch.workspace = true
common-runtime.workspace = true
common-telemetry.workspace = true
common-time.workspace = true
datafusion.workspace = true
datafusion-common.workspace = true
datafusion-expr.workspace = true
datafusion-functions.workspace = true
datafusion-optimizer.workspace = true
datafusion-physical-expr.workspace = true
datafusion-sql.workspace = true
datatypes.workspace = true
futures = "0.3"
futures-util.workspace = true
greptime-proto.workspace = true
humantime.workspace = true
itertools.workspace = true
lazy_static.workspace = true
log-query.workspace = true
meter-core.workspace = true
meter-macros.workspace = true
object-store.workspace = true
once_cell.workspace = true
prometheus.workspace = true
promql.workspace = true
promql-parser.workspace = true
prost.workspace = true
rand.workspace = true
regex.workspace = true
session.workspace = true
snafu.workspace = true
sql.workspace = true
sqlparser.workspace = true
store-api.workspace = true
substrait.workspace = true
table.workspace = true
tokio.workspace = true
uuid.workspace = true

[dev-dependencies]
approx_eq = "0.1"
arrow.workspace = true
catalog = { workspace = true, features = ["testing"] }
common-macro.workspace = true
common-query = { workspace = true, features = ["testing"] }
fastrand = "2.0"
format_num = "0.1"
num = "0.4"
num-traits = "0.2"
paste = "1.0"
pretty_assertions = "1.4.0"
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
session = { workspace = true, features = ["testing"] }
statrs = "0.16"
stats-cli = "3.0"
store-api.workspace = true
streaming-stats = "0.2"
table = { workspace = true, features = ["testing"] }
tokio-stream.workspace = true
