[package]
name = "common-pprof"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
common-error.workspace = true
common-macro.workspace = true
snafu.workspace = true
tokio.workspace = true

[target.'cfg(unix)'.dependencies]
pprof = { version = "0.14", features = [
    "flamegraph",
    "prost-codec",
    "protobuf",
] }

[lints]
workspace = true
