[package]
name = "common-grpc-expr"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
api = { path = "../../api" }
async-trait.workspace = true
common-base = { path = "../base" }
common-catalog = { path = "../catalog" }
common-error = { path = "../error" }
common-grpc = { path = "../grpc" }
common-query = { path = "../query" }
common-telemetry = { path = "../telemetry" }
common-time = { path = "../time" }
datatypes = { path = "../../datatypes" }
paste = "1.0"
snafu = { version = "0.7", features = ["backtraces"] }
table = { path = "../../table" }
