[package]
name = "common-event-recorder"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
api.workspace = true
async-trait.workspace = true
backon.workspace = true
common-error.workspace = true
common-macro.workspace = true
common-telemetry.workspace = true
common-time.workspace = true
humantime.workspace = true
humantime-serde.workspace = true
itertools.workspace = true
jsonb.workspace = true
serde.workspace = true
serde_json.workspace = true
snafu.workspace = true
store-api.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[lints]
workspace = true
