[package]
name = "common-config"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
common-base.workspace = true
humantime-serde.workspace = true
itertools.workspace = true
rskafka = "0.5"
serde.workspace = true
serde_json.workspace = true
serde_with = "3"
toml.workspace = true
