[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[alias]
sqlness = "run --bin sqlness-runner --"
sqlness-cli = "run --bin sqlness-cli --"

[build]
rustflags = [
    # lints
    # TODO: use lint configuration in cargo https://github.com/rust-lang/cargo/issues/5034
    "-Wclippy::print_stdout",
    "-Wclippy::print_stderr",
    "-Wclippy::implicit_clone",

    # It seems clippy has made a false positive decision here when upgrading rust toolchain to
    # nightly-2023-08-07, we do need it to be borrowed mutably.
    # Allow it for now; try disallow it when the toolchain is upgraded in the future.
    "-Aclippy::needless_pass_by_ref_mut",
]
