[package]
name = "api"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arrow-flight.workspace = true
common-base = { path = "../common/base" }
common-error = { path = "../common/error" }
common-time = { path = "../common/time" }
datatypes = { path = "../datatypes" }
greptime-proto = { git = "https://github.com/MichaelScofield/greptime-proto.git", rev = "94d603a098b10ee9b0c331b46356f31ea609d139" }
prost.workspace = true
snafu = { version = "0.7", features = ["backtraces"] }
tonic.workspace = true

[build-dependencies]
tonic-build = "0.8"
