[package]
name = "table"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
testing = []

[lints]
workspace = true

[dependencies]
api.workspace = true
async-trait.workspace = true
chrono.workspace = true
common-base.workspace = true
common-catalog.workspace = true
common-datasource.workspace = true
common-error.workspace = true
common-macro.workspace = true
common-query.workspace = true
common-recordbatch.workspace = true
common-telemetry.workspace = true
common-time.workspace = true
datafusion.workspace = true
datafusion-common.workspace = true
datafusion-expr.workspace = true
datafusion-physical-expr.workspace = true
datatypes.workspace = true
derive_builder.workspace = true
futures.workspace = true
greptime-proto.workspace = true
humantime.workspace = true
humantime-serde.workspace = true
lazy_static.workspace = true
paste.workspace = true
serde.workspace = true
snafu.workspace = true
store-api.workspace = true
tokio.workspace = true

[dev-dependencies]
common-test-util.workspace = true
parquet = { workspace = true, features = ["async"] }
serde_json.workspace = true
tokio-util = { version = "0.7", features = ["compat"] }
