[package]
name = "table"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
testing = []

[dependencies]
anymap = "1.0.0-beta.2"
async-trait = "0.1"
chrono.workspace = true
common-base = { path = "../common/base" }
common-catalog = { path = "../common/catalog" }
common-error = { path = "../common/error" }
common-procedure = { path = "../common/procedure" }
common-query = { path = "../common/query" }
common-recordbatch = { path = "../common/recordbatch" }
common-telemetry = { path = "../common/telemetry" }
common-time = { path = "../common/time" }
datafusion.workspace = true
datafusion-common.workspace = true
datafusion-expr.workspace = true
datafusion-physical-expr.workspace = true
datatypes = { path = "../datatypes" }
derive_builder.workspace = true
futures.workspace = true
humantime = "2.1"
humantime-serde = "1.1"
parquet-format-async-temp = "0.2"
paste = "1.0"
serde = "1.0.136"
snafu = { version = "0.7", features = ["backtraces"] }
store-api = { path = "../store-api" }
tokio.workspace = true

[dev-dependencies]
common-test-util = { path = "../common/test-util" }
parquet = { workspace = true, features = ["async"] }
tokio-util = { version = "0.7", features = ["compat"] }
serde_json.workspace = true
