[package]
name = "table-procedure"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
catalog = { path = "../catalog" }
common-error = { path = "../common/error" }
common-procedure = { path = "../common/procedure" }
common-telemetry = { path = "../common/telemetry" }
datatypes = { path = "../datatypes" }
serde.workspace = true
serde_json.workspace = true
snafu.workspace = true
table = { path = "../table" }

[dev-dependencies]
log-store = { path = "../log-store" }
mito = { path = "../mito" }
object-store = { path = "../object-store" }
storage = { path = "../storage" }
tokio.workspace = true
tempfile = "3.4.0"
