[package]
name = "common-base"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
bitvec = "1.0"
bytes = { version = "1.1", features = ["serde"] }
common-error = { path = "../error" }
paste = "1.0"
serde = { version = "1.0", features = ["derive"] }
snafu = { version = "0.7", features = ["backtraces"] }
rustls = "0.20"
rustls-pemfile = "1.0"
