[package]
name = "common-base"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anymap = "1.0.0-beta.2"
bitvec = "1.0"
bytes.workspace = true
common-error.workspace = true
common-macro.workspace = true
paste = "1.0"
serde = { version = "1.0", features = ["derive"] }
snafu.workspace = true

[dev-dependencies]
toml.workspace = true
