[package]
name = "storage"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arc-swap = "1.0"
async-compat = "0.2"
async-stream.workspace = true
async-trait = "0.1"
arrow.workspace = true
arrow-array.workspace = true
bytes = "1.1"
common-base = { path = "../common/base" }
common-datasource = { path = "../common/datasource" }
common-error = { path = "../common/error" }
common-query = { path = "../common/query" }
common-recordbatch = { path = "../common/recordbatch" }
common-runtime = { path = "../common/runtime" }
common-telemetry = { path = "../common/telemetry" }
common-time = { path = "../common/time" }
datatypes = { path = "../datatypes" }
datafusion-common.workspace = true
datafusion-expr.workspace = true
futures.workspace = true
futures-util.workspace = true
itertools = "0.10"
lazy_static = "1.4"
metrics.workspace = true
object-store = { path = "../object-store" }
parquet = { workspace = true, features = ["async"] }
paste.workspace = true
planus = "0.2"
prost.workspace = true
regex = "1.5"
serde.workspace = true
serde_json = "1.0"
sluice = "0.5"
snafu = { version = "0.7", features = ["backtraces"] }
store-api = { path = "../store-api" }
table = { path = "../table" }
tokio.workspace = true
tokio-util.workspace = true
tonic.workspace = true
uuid.workspace = true

[dev-dependencies]
atomic_float = "0.1"
criterion = "0.3"
common-test-util = { path = "../common/test-util" }
datatypes = { path = "../datatypes", features = ["test"] }
log-store = { path = "../log-store" }
rand.workspace = true

[build-dependencies]
tonic-build = "0.9"

[[bench]]
name = "bench_main"
harness = false
