[package]
name = "storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arc-swap = "1.0"
arrow-format = { version = "0.4", features = ["ipc"] }
async-stream = "0.3"
async-trait = "0.1"
bytes = "1.1"
common-base = { path = "../common/base" }
common-error = { path = "../common/error" }
common-runtime = { path = "../common/runtime" }
common-telemetry = { path = "../common/telemetry" }
common-time = { path = "../common/time" }
datatypes = { path = "../datatypes" }
futures = "0.3"
futures-util = "0.3"
lazy_static = "1.4"
log-store = { path = "../log-store" }
object-store = { path = "../object-store" }
paste = "1.0"
planus = "0.2"
prost = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
snafu = { version = "0.7", features = ["backtraces"] }
store-api = { path = "../store-api" }
regex = "1.5"
tokio = { version = "1.18", features = ["full"] }
tonic = "0.8"
uuid = { version = "1.1" , features=["v4"]}

[dev-dependencies]
atomic_float="0.1"
criterion = "0.3"
datatypes = { path = "../datatypes", features = ["test"] }
rand = "0.8"
tempdir = "0.3"

[build-dependencies]
tonic-build = "0.8"

[[bench]]
name = "bench_main"
harness = false
