[package]
name = "storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arc-swap = "1.0"
async-trait = "0.1"
common-error = { path = "../common/error" }
common-telemetry = { path = "../common/telemetry" }
datatypes = { path = "../datatypes" }
snafu = { version = "0.7", features = ["backtraces"] }
store-api = { path = "../store-api" }
tokio = { version = "1.18", features = ["full"] }
