[package]
name = "metric-engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
api.workspace = true
async-trait.workspace = true
base64 = "0.21"
common-error.workspace = true
common-macro.workspace = true
common-query.workspace = true
common-recordbatch.workspace = true
common-time.workspace = true
datatypes.workspace = true
mito2 = { workspace = true, features = ["test"] }
object-store.workspace = true
serde_json.workspace = true
snafu.workspace = true
store-api.workspace = true
