[package]
name = "metric-engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
api.workspace = true
aquamarine.workspace = true
async-trait.workspace = true
base64.workspace = true
common-error.workspace = true
common-macro.workspace = true
common-query.workspace = true
common-recordbatch.workspace = true
common-telemetry.workspace = true
common-time.workspace = true
datafusion.workspace = true
datatypes.workspace = true
lazy_static = "1.4"
mito2.workspace = true
mur3 = "0.1"
object-store.workspace = true
prometheus.workspace = true
serde_json.workspace = true
snafu.workspace = true
store-api.workspace = true
tokio.workspace = true

[dev-dependencies]
common-test-util.workspace = true
mito2 = { workspace = true, features = ["test"] }
