[package]
name = "common-macro"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
backtrace = "0.3"
common-telemetry = { workspace = true }
proc-macro2 = "1.0.66"
quote = "1.0"
syn = "1.0"

[dev-dependencies]
arc-swap = "1.0"
common-query = { workspace = true }
datatypes = { workspace = true }
snafu.workspace = true
static_assertions = "1.1.0"
