[package]
name = "store-api"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
api.workspace = true
aquamarine.workspace = true
async-trait.workspace = true
common-base.workspace = true
common-error.workspace = true
common-grpc.workspace = true
common-macro.workspace = true
common-recordbatch.workspace = true
common-time.workspace = true
common-wal.workspace = true
datafusion-expr.workspace = true
datafusion-physical-plan.workspace = true
datatypes.workspace = true
derive_builder.workspace = true
futures.workspace = true
humantime.workspace = true
lazy_static.workspace = true
prometheus.workspace = true
prost.workspace = true
serde.workspace = true
serde_json.workspace = true
snafu.workspace = true
strum.workspace = true
tokio.workspace = true

[dev-dependencies]
async-stream.workspace = true
common-meta.workspace = true
serde_json.workspace = true
